CREATE TABLE TESTSCHEMA.FEEDBACK
    (
		ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
        ORIGINAL_FEEDBACK VARCHAR(2000),
        LANGUAGE CHAR(2),
        ENGLISH_FEEDBACK VARCHAR(2000),
        SENTIMENT CHAR(8),
        ANGER DECIMAL(5,2),
        FEAR DECIMAL(5,2),
        JOY DECIMAL(5,2),
        SADNESS DECIMAL(5,2),
        KEYWORDS VARCHAR(2000)
    )